;;;; mymod.import.scm - GENERATED BY CHICKEN 5.1.0 -*- Scheme -*-

(##sys#register-compiled-module
  'mymod
  'mymod
  (scheme#list)
  '((hello . mymod#hello))
  (scheme#list)
  (scheme#list))

;; END OF FILE
