;;;; grades.import.scm - GENERATED BY CHICKEN 5.1.0 -*- Scheme -*-

(scheme#eval '(import-syntax scheme chicken.base))
(##sys#register-compiled-module
  'grades
  'grades
  (scheme#list)
  '((gpa->grade . grades#gpa->grade) (letter->number . grades#letter->number))
  (scheme#list
    (scheme#cons
      'gpa
      (syntax-rules
        ()
        ((_ g1 g2 ...)
         (let ((ls (map letter->number `(g1 g2 ...))))
           (/ (apply + ls) (length ls)))))))
  (scheme#list
    (scheme#cons
      'range-case
      (syntax-rules
        (- else)
        ((_ expr ((x - y) e1 e2 ...) ... (else ee1 ee2 ...))
         (let ((tmp expr))
           (cond ((in-range? x tmp y) e1 e2 ...) ... (else ee1 ee2 ...))))
        ((_ expr ((x - y) e1 e2 ...) ...)
         (let ((tmp expr)) (cond ((in-range? x tmp y) e1 e2 ...) ...)))))))

;; END OF FILE
