;;;; mymod.import.scm - GENERATED BY CHICKEN 5.1.0 -*- Scheme -*-

(scheme#eval '(import-syntax scheme))
(##sys#register-compiled-module
  'mymod
  'mymod
  (scheme#list)
  '((hello . mymod#hello) (print-x . mymod#print-x))
  (scheme#list
    (scheme#cons 'greet (syntax-rules () ((_ g1 g2 ...) (print-x "Hello")))))
  (scheme#list))

;; END OF FILE
