;;;; grades.import.scm - GENERATED BY CHICKEN 5.1.0 -*- Scheme -*-

(scheme#eval '(import-syntax scheme chicken.base))
(##sys#register-compiled-module
  'grades
  'grades
  (scheme#list)
  '((gpa->grade . grades#gpa->grade)
    (letter->number . grades#letter->number)
    (filter . grades#filter)
    (cnt . grades#cnt)
    (histogram . grades#histogram))
  (scheme#list
    (scheme#cons
      'distribution
      (syntax-rules
        ()
        ((_ g1 g2 ...)
         (map (lambda (x) (list (cnt `(g1 g2 ...) (lambda (y) (eqv? y x))) x))
              `(a b c d e f)))))
    (scheme#cons
      'gpa
      (syntax-rules
        ()
        ((_ g1 g2 ...)
         (let ((ls (map letter->number
                        (filter `(g1 g2 ...) (lambda (x) (not (eqv? x 'x)))))))
           (if (null? ls) 0.0 (/ (apply + ls) (length ls))))))))
  (scheme#list
    (scheme#cons
      'range-case
      (syntax-rules
        (- else)
        ((_ expr ((x - y) e1 e2 ...) ... (else ee1 ee2 ...))
         (let ((tmp expr))
           (cond ((in-range? x tmp y) e1 e2 ...) ... (else ee1 ee2 ...))))
        ((_ expr ((x - y) e1 e2 ...) ...)
         (let ((tmp expr)) (cond ((in-range? x tmp y) e1 e2 ...) ...)))))))

;; END OF FILE
